name: Install and TS compile on all OSes

on:
  push:
    branches: [ "master", "master-for-develop", "master-for-staging" ]
  pull_request:
    branches: [ "master", "master-for-develop", "master-for-staging" ]
  workflow_dispatch:

jobs:
  build:
    
    strategy:
      matrix:
        # Available GitHub-hosted runner types, see:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        os: [windows-latest, ubuntu-latest, macos-latest, windows-2019, ubuntu-20.04, macos-11]
        # Available Node versions for GitHub actions, see:
        # https://github.com/actions/node-versions/releases
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    
#    defaults:
#      run:
#        shell: bash
#        working-directory: Source

    steps:
      - uses: actions/checkout@v4
      - name: Install and TS compile in Node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
        shell: bash
      # Test installing with npm
      - run: |
          npm i
          npm run tsc-win
      # Test installing with yarn
      - run: |
          npm i -g yarn
          yarn
          yarn tsc-win



